In [9]:
import pandas as pd

In [10]:
caseStudyDf = pd.read_csv("/home/alextay96/Desktop/all_workspace/new_workspace/DLDataPipeline/data/case_study/case_study_8/case_study_result.csv")

In [11]:
labelErrorDf = caseStudyDf[caseStudyDf["remarks"] == "label error"]
labelErrorByPartDf = labelErrorDf.groupby(["part"])["CaseID"].count().reset_index().rename(columns={"CaseID" : "count"})
labelErrorByPartDf.sort_values(by="count", ascending=False, inplace=True)
labelErrorByPartDf["ratio"] = labelErrorByPartDf["count"] / len(caseStudyDf["CaseID"].unique())
labelErrorByPartDf

                part  count     ratio
2       bumper_front      8  0.266667
11       front_panel      5  0.166667
1             bonnet      5  0.166667
12            grille      5  0.166667
9    fender_front_lh      5  0.166667
14       headlamp_rh      4  0.133333
8             engine      4  0.133333
19             wheel      2  0.066667
16        rear_panel      2  0.066667
15  rear_compartment      2  0.066667
21   windscreen_rear      2  0.066667
10   fender_front_rh      2  0.066667
3        bumper_rear      2  0.066667
7       door_rear_rh      1  0.033333
13       headlamp_lh      1  0.033333
6       door_rear_lh      1  0.033333
5      door_front_rh      1  0.033333
4        cooling_fan      1  0.033333
17      tail_lamp_lh      1  0.033333
18      tail_lamp_rh      1  0.033333
20  windscreen_front      1  0.033333
0   air_conditioning      1  0.033333

In [12]:
predErrorDf = caseStudyDf[caseStudyDf["remarks"] == "error"]
predErrorByPartDf = predErrorDf.groupby(["part", "fp", "fn"])["CaseID"].count().reset_index().rename(columns={"CaseID" : "count"})
predErrorByPartDf.sort_values(by="count", ascending=False, inplace=True)
predErrorByPartDf["ratio"] = predErrorByPartDf["count"] / len(caseStudyDf["CaseID"].unique())
predErrorByPartDf

                part  fp  fn  count     ratio
3        bumper_rear   1   0      4  0.133333
4             engine   1   0      3  0.100000
10       headlamp_lh   1   0      3  0.100000
2       bumper_front   1   0      2  0.066667
6    fender_front_rh   0   1      2  0.066667
0   air_conditioning   0   0      1  0.033333
1       bumper_front   0   0      1  0.033333
5    fender_front_lh   0   1      1  0.033333
7        front_panel   0   1      1  0.033333
8             grille   1   0      1  0.033333
9        headlamp_lh   0   1      1  0.033333
11       headlamp_rh   1   0      1  0.033333
12  rear_compartment   1   0      1  0.033333
13             wheel   1   0      1  0.033333

In [13]:
tempDf = caseStudyDf[caseStudyDf["remarks"] == "label error"]
countDf = tempDf.groupby("CaseID")["remarks"].count().reset_index().rename(columns={
    "remarks" : "label_error_count"
})
countDf["after_repair_img"] = countDf["label_error_count"].apply(lambda x : x > 2)
countDf[countDf["after_repair_img"] == True]

      CaseID  label_error_count  after_repair_img
7   10353034                  7              True
8   10485749                  4              True
9   10618351                  3              True
10  10983278                  4              True
14  11741614                  5              True
15  11746258                  5              True
20  12628126                  3              True

In [14]:
afterRepairError = 7 / 30
afterRepairError

0.23333333333333334

In [15]:
labelErrorButCorrectDf = caseStudyDf[(caseStudyDf["remarks"] == "label error") & (caseStudyDf["pred"] == caseStudyDf["gt"] )]
labelErrorButCorrectByPartDf = labelErrorButCorrectDf.groupby(["part"])["CaseID"].count().reset_index().rename(columns={"CaseID" : "count"})
labelErrorButCorrectByPartDf.sort_values(by="count", ascending=False, inplace=True)
labelErrorButCorrectByPartDf["ratio"] = labelErrorButCorrectByPartDf["count"] / len(caseStudyDf["CaseID"].unique())
labelErrorButCorrectByPartDf

               part  count     ratio
2      bumper_front      5  0.166667
1            bonnet      2  0.066667
3       bumper_rear      2  0.066667
7  rear_compartment      2  0.066667
0  air_conditioning      1  0.033333
4      door_rear_lh      1  0.033333
5            engine      1  0.033333
6       headlamp_rh      1  0.033333
8  windscreen_front      1  0.033333

In [16]:
labelErrorButIncorrectDf = caseStudyDf[(caseStudyDf["remarks"] == "label error") & (caseStudyDf["pred"] != caseStudyDf["gt"] )]
labelErrorButIncorrectByPartDf = labelErrorButIncorrectDf.groupby(["part"])["CaseID"].count().reset_index().rename(columns={"CaseID" : "count"})
labelErrorButIncorrectByPartDf.sort_values(by="count", ascending=False, inplace=True)
labelErrorButIncorrectByPartDf["ratio"] = labelErrorButIncorrectByPartDf["count"] / len(caseStudyDf["CaseID"].unique())
labelErrorButIncorrectByPartDf

               part  count     ratio
8       front_panel      5  0.166667
6   fender_front_lh      5  0.166667
9            grille      5  0.166667
11      headlamp_rh      3  0.100000
1      bumper_front      3  0.100000
0            bonnet      3  0.100000
5            engine      3  0.100000
7   fender_front_rh      2  0.066667
12       rear_panel      2  0.066667
15            wheel      2  0.066667
16  windscreen_rear      2  0.066667
4      door_rear_rh      1  0.033333
3     door_front_rh      1  0.033333
10      headlamp_lh      1  0.033333
2       cooling_fan      1  0.033333
13     tail_lamp_lh      1  0.033333
14     tail_lamp_rh      1  0.033333